### ISSUE TITLE
how to use with nextjs

### ISSUE THREAD

**Issue by alidcastano** [zendeskgarden/react-components#10]
## Expectations
Should work after configuring css modules:

```
const withCss = require('@zeit/next-css')
module.exports = withCss({
  cssModules: true
})
```

## Reality

Getting CSS compilation error for View components. For the Container components I'm getting `Element is not defined error.`

## Steps to Reproduce

Any next starter with Garden.

**Comment by austin94** [comment]
👋 Hi @alidcastano, thanks for opening this issue.

The last time I did any development with `next.js` was a long time ago, but if I remember correctly, it was _uniquely_ difficult to get external CSS (and css-modules) working correctly.

I haven't used their `next-css` package since it's been introduced so I'm going to do some research and post my findings here.

**Comment by austin94** [comment]
After doing some research into this I found a variety of issues.

1. Due to our usage of css-modules a user would need to configure `withCss` to run against `/node_modules/` as well as local imports
1. The `ThemeProvider` component in `@zendeskgarden/react-theming` includes some configuration that will fail in a node environment

## CSS-Modules

I was able to get this working correctly by following the [official with-next-css example](https://github.com/zeit/next.js/tree/canary/examples/with-next-css). You can use the `webpack` config option to update the loaders to allow it to resolve for `/node_modules/` as well as local files.

This should fix the `.c-btn is not defined` error you would have been seeing in the Views.

## Theming issues

Within our `ThemeProvider` component we are embedding our own `StyleSheetManger` component from `styled-components`. This should ideally only be provided by the consumer as a wrapper around the root React component.

Additionally, we are referencing some browser only APIs like `document.head` and `Element`. This is whats causing the `Element is not defined...` errors.

@ryanseddon what do you think?

**Comment by alidcastano** [comment]
Hey @austin94, what exactly did you edit? I wasn't able to get it to work. E.g. I tried getting the ccs rule and doing `rule.include =/node_modules\/@zendeskgarden\/css/`.

In regards to SSR, I'd love to see this addressed since it's something I'll be needing for my project. But for now I've started out with create-react-app. 

Thanks!

**Comment by ryanseddon** [comment]
Not making assumptions about running in a browser context is definitely something we should do. 

I've created a card on our internal backlog to look at this, haven't prioritised it yet.

**Comment by sunesimonsen** [comment]
I think it makes sense to create a FAQ with entries like: Running Garden React Components with CSS Modules, ...

**Comment by austin94** [comment]
> I think it makes sense to create a FAQ

Definitely. We already (kind of) have an example of "usage with create-react-app". We should definitely expand that to everything.

Some entries off the top of my head are:
- Usage with create-react-app
- Usage with CSS Modules
- Webpack 4 configuration (maybe 3 as well)
- Next.js example usage

**Comment by ryanseddon** [comment]
@alidcastano As of yesterday garden will now work with next.js!

You no longer need to turn on CSS modules.

In `next.config.js`:

```js
const withCSS = require('@zeit/next-css');

module.exports = withCSS();
```

In `pages/index.js`:

```js
import { ThemeProvider } from '@zendeskgarden/react-theming';
import { Button } from '@zendeskgarden/react-buttons';

import '@zendeskgarden/react-buttons/dist/styles.css';

export default () => (
  <ThemeProvider>
    <Button>Hello</Button>
  </ThemeProvider>
);
```

Garden also has a few peer dependecies you'll have to install explicity now:

- @zendeskgarden/react-theming
- styled-components
- react & react-dom (you'll have these as part of next.js)

**Comment by ryanseddon** [comment]
I'm gonna close this out as we've fixed the initial issue, we'll have a story on our backlog to follow up on the FAQ guides.
