### ISSUE TITLE
pass styles to view component directly

### ISSUE THREAD

**Issue by alidcastano** [zendeskgarden/react-components#11]
This is a question, and possibly a feature request.

Why can't we just pass the style overrides to each component directly?

```
 <ExampleView styles={styleOverrides}>
```

versus

```
<ThemeProvider  styles={styleOverrides}>
    <ExampleView>
</ThemeProvider>
```

I'm new to React so not sure if there is a drawback or limitation that caused you guys to go with the second method. But I don't see why each component can't handle injecting its own style overrides.

So maybe instead of doing this in the code ` ${props => retrieveTheme(COMPONENT_ID, props)};` it can just be this `${props => props.styles}`

**Comment by alidcastano** [comment]
Also I'm not sure if I'm even doing the above correctly. Say I wanted to change the `MenuView` styles.

Is the code below suppose to work?

```
const menuViewStyles = {
  'menus.menu_view': `
    border: 1px solid blue;
  `
}

<ThemeProvider  styles={menuViewStyles}>
   <MenuView {...}>...</MenuView>
</ThemeProvider>
```

**Comment by austin94** [comment]
👋 Hi @alidcastano, thanks for the discussion.

> Why can't we just pass the style overrides to each component directly?

You can! All of of view components accept 100% of their native props (including `style/className/etc.`). Here is an example from our [buttons documentation](https://garden.zendesk.com/react-components/buttons/#button) (you can edit the demos to play around with anything).

![screen shot 2018-05-14 at 9 03 34 am](https://user-images.githubusercontent.com/4030377/40009146-0f330da0-5756-11e8-9f4c-a858edb73d40.png)

> But I don't see why each component can't handle injecting its own style overrides.

The purpose of having a `ThemeProvider` is to provide _global_ styling. Each view is able to be styled individually, but lets say a consumer wants to modify the padding of every `MenuView` in their project. That is a good use-case for the `ThemeProvider`.

> Also I'm not sure if I'm even doing the above correctly. Say I wanted to change the MenuView styles.

One of the main issues with theming that you see in shared libraries (including ours) is that any custom styles have to beat the specificity of the existing styling. One way to do this with standard CSS is to use:

```jsx
const menuViewStyles = {
  'menus.menu_view': `
    && {
        border: 1px solid blue;
    }
  `
};
```

Using a `ThemeProvider` works well for small, global tweaks. But it can be hard to maintain since CSS specificity is finicky and can change over time as new styles are added.

The main point of of the `Element/Container/View` split in these packages are to allow the freedom to _not_ need to use the `ThemeProvider`.  You can provide your own `MenuView`, style it with the style/className props, or wrap it in a CSS-in-JS library. A styled-components example would be:

```jsx
import GardenButton from '@zendeskgarden/react-buttons/Button';
import styled from 'styled-components';

const CustomButton = styled(GardenButton)`
    color: red;
    margin: 8px;
`;

export default props => <CustomButton {...props} />;
```

> I'm guessing the key for the styles is the COMPONENT_ID referenced in the code.

If you want to easily find a Views component ID, you can look in the DOM for the `data-garden-id` attributes. These match the COMPONENT_ID used for theming.

**Comment by alidcastano** [comment]
Great explanation! Thanks.

Yes,[ the Element/Container/View split is what I like most about this library](https://twitter.com/alidcastano/status/994724966884102144). :) But I was creating my own View components from scratch, I didn't think about passing the original component to the `styled` function, which will make things much easier.

I think the documentation would greatly benefit from a getting started section with these sort of explanations. The code examples are great but maybe as issues like this are raised, they'll be enough material to create one and make onboarding even smoother.

Anyway, I'll go ahead and close this, thanks!

**Comment by jzempel** [comment]
@alidcastano thanks so much for the issue. Totally agreed on the documentation – conversations like this go a long way toward helping us get our newly open-sourced project improved and understandable.

Cheers!
