### ISSUE TITLE
object doesn't support property or method 'values'

### ISSUE THREAD

**Issue by SabaRathnamK** [zendeskgarden/react-components#121]
React-Select. This error occur only in ie11 once I click the selectbox element.

**Comment by austin94** [comment]
👋 Hi @SabaRathnamK. I'm having some issues reproducing this in IE11 with our current documentation. 

Could you create a https://codesandbox.io/ with a live example or provide a screenshot with the related error message?

**Comment by SabaRathnamK** [comment]
Here's the link

https://codesandbox.io/s/1x1pvz5z7

**Comment by SabaRathnamK** [comment]
![pastedimage](https://user-images.githubusercontent.com/39154180/44511536-87b79380-a6d5-11e8-8604-64063a295a09.png)

**Comment by austin94** [comment]
@SabaRathnamK thanks for providing the codepen. I think I've found the issue!

## Reproduction

Our styleguide (and internal Zendesk products) currently include some common IE11 runtime polyfills which is why this slipped through.

The issue was actually in our `getPopperPlacements` method in `@zendeskgarden/react-tooltips` which is a dependency of `react-select`.

## Fix

The easiest fix is to refactor this area to use IE11 compliant logic (no `Object.values()`)

**Comment by austin94** [comment]
@SabaRathnamK this should be fixed with the following releases:

- `@zendeskgarden/react-tooltips@4.3.8`
- `@zendeskgarden/react-menus@3.5.9`
- `@zendeskgarden/react-autocomplete@0.1.27`
- `@zendeskgarden/react-select@2.3.10`

Unrelated, but I noticed in your codepen that you are theming the components with the css class names provided by css-modules. These are unique for every release and will break in the future.

For doing small theming you can use the [ThemeProvider](https://garden.zendesk.com/react-components/theming/). For larger styling (like your example) you are able to use our Container components to apply the interaction and accessibility logic onto _ANY_ components, not just Garden.

This is best shown in a blog post that @ryanseddon posted a while ago. https://medium.com/zendesk-engineering/creating-the-ultimate-flexibility-via-container-components-in-react-e4b8eca5338c . The example given is for `Tabs`, but it is applicable to all Garden components.
