### ISSUE TITLE
Field - child elements rendered with font-size: 0

### ISSUE THREAD

**Issue by albertfdp** [zendeskgarden/react-components#1490]
## Expectations

It should be possible to render `<Anchor />` tags and other elements as child of `<Field />`

## Reality

Tags that implement `font-size: inherit` result in not being rendered when child or nested child of `Field` as it implements `font-size: 0`. (Introduced in https://github.com/zendeskgarden/react-components/pull/1076/files#diff-5a92bfca891e0c20d051635b3021272225e65bd3115c8af399fea8abfe933944R27)

This results in elements unexpectedly disappearing from previous versions behavior.

### Before 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/649667/213161866-6abaada0-31f2-4c35-bf35-fbc41f1c0ce6.png">

### After

<img width="433" alt="image" src="https://user-images.githubusercontent.com/649667/213162020-71160bc4-06c5-46b1-a456-dab43f12af5e.png">

## Steps to Reproduce

1. Import `Field` from `react-forms`
2. Import `Anchor` from `react-buttons` (it can also be a `<div />`)
3. Render 

```jsx
<Field><Anchor>Hello world</Anchor></Field>
```

Example here: https://codesandbox.io/s/exciting-currying-ife3u5?file=/src/Example.tsx

### Fine Print

- Component: Field
- Version: ^8.37.0
- Browsers: all

**Comment by Francois-Esquire** [comment]
Hey @albertfdp thanks for reporting this, will be looking into this with the team.

**Comment by jzempel** [comment]
@albertfdp this along with a number of a11y violations is fixed with Garden's new `Combobox`. Please see the following references for details:
- https://www.npmjs.com/package/@zendeskgarden/react-dropdowns.next
- https://zendeskgarden.github.io/react-components/?path=/story/packages-dropdowns-next-combobox--uncontrolled
- https://codesandbox.io/s/combobox-demo-vhhlgh?file=/src/ComboboxNext.tsx
