### ISSUE TITLE
Textfield-Checkbox ID collision

### ISSUE THREAD

**Issue by aravindet** [zendeskgarden/react-components#157]
## Expectations

HTML IDs should not collide. Clicking on a label should reliably focus the input next to it.

Also it should be possible to use different packages at slightly different versions (as long as peer dependencies are satisfied).

## Reality

I have a form with some text inputs and checkboxes as siblings. The rendered DOM contains:

```html
<input data-garden-id="textfields.input" data-garden-version="3.3.6"
  ... id="garden-0--input" ... >

...

<input type="checkbox" data-garden-id="checkboxes.input" data-garden-version="3.3.5"
  ... id="garden-0--input" ... >
```

As you can see, the `data-garden-version` differs by a patch increment and the id (`garden-0--input`) clashes.

The root cause seems to be that each package has `react-selection` as a dependency, and this brings in two copies of `IdManager`. As the Id Manager uses a module-local variable to keep sequential IDs, this is guaranteed to clash.

## Steps to Reproduce

1. Install two versions of textfields and checkbox so that they bring in different versions of react-selection.
2. Put a checkbox (using `<Checkbox>`) and a text input (using `<TextField>`) on the same page so they are rendered at the same time.
3. Clicking the label of the second one (in DOM order) will focus the first input.

## Suggestions

1. Use UUID
2. Use a different suffix/prefix in the IDs for each package. E.g. `garden-0--checkbox-input`.
3. Make the ID counter global (window.idCounter?)
4. Put the ID counter in some sort of Provider
...

###### Fine Print

* Component: Checkbox, Textfields, Radio?
* Browsers: all

**Comment by austin94** [comment]
Hi @aravindet, thanks for opening the issue.

This shouldn't be happening by default, the `IdManger` utility is already using a globally available context.

Could you ensure that there is only a single `react-selection` package within your bundle? If there are duplicate IDs it normally means there is a duplicated `IdManger` somewhere.

> Use a different suffix/prefix in the IDs for each package

Not sure this will fix the root-cause of the issue, but it could help mitigate it some.  We already have the ability to customize the ID prefix so this would be an easy addition.

**Comment by ryanseddon** [comment]
So to add to this a few teams have had this in melbourne, due to having an older version of checkboxes e.g. checkboxes@2.0.1 has a dependency on react-selection@3.0.1 so if you added react-textfields@3.3.5 it would have react-selection@4.5.0 so yarns deduping wouldn't dedupe the package as it is a major version bump between them.

See reduced [test case](https://codesandbox.io/s/j775875nxw).

> This shouldn't be happening by default, the IdManger utility is already using a globally available context.

The `let idCounter = 0;` is scoped to the package and is not a global shared between all packages. So with the above test case checkboxes references a different `idCounter` to textfields.

Best option moving forward would be to use a unique suffix/prefix so we still have stable ids for SSR.

**Comment by aravindet** [comment]
@ryanseddon Yup, that's exactly what's happening.
