### ISSUE TITLE
Tables with auto column width

### ISSUE THREAD

**Issue by aravindet** [zendeskgarden/react-components#160]
## Expectations

It should be possible to create tables where the widths of columns are determined by the content in the cells.

Additionally, the Garden specs call for sticky headers on long tables.

## Reality

With the move to flex, all cells are required to have explicit widths. Even when we were using HTML tables, all cells required explicit widths 

## Suggestion

Use CSS Grid to permit both auto-column-width and sticky headers at the same time.

https://codepen.io/aravindet/pen/WggmWR

Caveats:

- The DOM structure is Table > Cell, there is no DOM element corresponding to a Row. This has implications on how styling is applied.
- To support IE11, each cell requires some inline styling (`-ms-grid-row` and `-ms-grid-column`).
- IE11 does not support position:sticky, but sticky headers can be considered a progressive enhancement.

###### Fine Print

* Component: Tables
* Browsers: all

**Comment by ryanseddon** [comment]
I'm wondering what the a11y implications here are of using a grid? Since we can't specify rows and cells we can do cells but they need to be in a row for the a11y dev tools to pick up a proper grid.

### Grid with `role`'s applied
![image](https://user-images.githubusercontent.com/143402/45728024-85c7ee00-bc09-11e8-9bfd-cd22af0ab71b.png)

### Current flexbox based grid
![image](https://user-images.githubusercontent.com/143402/45729971-7ac58b80-bc12-11e8-9e73-fcca0d097a0b.png)

I'm not sure without further testing how a screenreader may step through something done with css grid over flexbox but definitely see that grid is the better option for acting more like an actual table.

**Comment by jzempel** [comment]
From what I understand, CSS grid with auto-layout is a no-go for IE11. Wouldn’t that be required for a general purpose table component?

**Comment by aravindet** [comment]
@jzempel On IE11 the React component would calculate and add `-ms-grid-row` and `-ms-grid-column` CSS properties (perhaps inline?) to each cell. This simulates auto layout from the perspective of the consumer.

The calculation is trivial in the absence of colspan and rowspan (and not too hard even then). The requirement is limited to simulating a table (and not reimplementing all the nuances of CSS grid auto layout).
