### ISSUE TITLE
Dots Loader is extremely slow

### ISSUE THREAD

**Issue by aravindet** [zendeskgarden/react-components#164]
## Expectations

Computer should remain responsive when UI using the Dots loader is displayed

## Reality

Computer slows down with chrome hitting >70% CPU on 2016 MBP.

## Steps to Reproduce

- Go to https://garden.zendesk.com/react-components/loaders/#dots (keep this tab in the foreground)
- Open the Chrome Task Manager and wait a few seconds

## Suggestion

Consider implementing the animation using CSS animations or SMIL rather than React.

###### Fine Print

* Component: Dots Loader
* Browsers: Chrome on macOS

**Comment by ryanseddon** [comment]
Thanks @aravindet definitely don't want to introduce a perf issue, I created a [reduced test case](https://3r68llnk01.codesandbox.io/) with just the loader and I'm getting about 19 - 22% cpu usage for a single loader. 

This is still pretty high but not super bad. Are you seeing this CPU utilisation in your implementation and not just on the docs site?

I also ran a profile on both

### Reduced test case perf
![image](https://user-images.githubusercontent.com/143402/45935573-04e56980-bff0-11e8-86dd-831a091f9ce1.png)

### Docs site

![image](https://user-images.githubusercontent.com/143402/45935617-6c9bb480-bff0-11e8-9403-20829c9be685.png)

Seems on the docs site the CPU usage is due to the high number of loaders on the pager at once, reducing it to a [single one](https://garden.zendesk.com/react-components/loaders/#!/Dots/1) sees the CPU usage drop to the same as the reduced test case.

However if we can programatically generate a CSS animation version that performs even better I'm all for it, I'm currently working on the spinner component and will explore that too and make sure perf is not an issue.

**Comment by aravindet** [comment]
I'm programmatically creating a CSS animation using styled-components here: https://github.com/zendesk/polaris-components/blob/master/packages/serve-button/src/Dots.js

Granted that animation is much simpler than this one; as long as you can define the movement of each dot using keyframes and easing it should be possible.

**Comment by jzempel** [comment]
@aravindet we already have the pure CSS `keyframes` approach for both Dots and Spinner loaders. https://github.com/zendeskgarden/css-components/tree/jzempel/loaders/packages/loaders/src Unfortunately, as Austin mentions, these don't work in IE11.

**Comment by aravindet** [comment]
@ryanseddon thanks for clarifying. I think general perf improvements are always helpful, but I'll close out this issue as there isn't an immediate bug. Incidentally the CSS animations used in Polaris somehow do work on IE11. 🤷‍♂️
