### ISSUE TITLE
Menu trigger is focused on mouse interaction

### ISSUE THREAD

**Issue by aravindet** [zendeskgarden/react-components#173]
## Expectations

When I only use a mouse, focus affordances (shadows, highlights) should not be shown.

## Reality

When a menu is shown and then closed by clicking one of the options, the trigger of the menu (typically a button) shows a focus affordance.

## Steps to Reproduce

- Go to https://garden.zendesk.com/react-components/menus/
- Click a button to show a menu
- Click a menu item
- If an alert is shown, dismiss it
- The button is focused.

###### Fine Print

* Component: Menu
* Browsers: all

**Comment by austin94** [comment]
This is actually "as designed" currently. Definitely something that we can approach with fresh eyes though.

Disregarding the visuals, we must return the focus state to the trigger for accessibility reasons. This brings users back into the original tab order (since the menu is placed relative to `<body>`) as well as re-reads the trigger state to the screen reader.

On the visual side, we could not show the focus ring specifically for this interaction, but personally I like seeing where I am being returned to. @allisonacs and @jzempel do you have any thoughts?

**Comment by jzempel** [comment]
@austin94 we don't want visual focus treatment on the trigger after mouse action on the menu. We might want to show visual focus when keyboard is used for menu item selection. But that will be a game-time decision for @allisonacs to make. Note: this doesn't affect current `<Select>` behavior where the input field remains visually focused as the menu is acted upon.
