### ISSUE TITLE
Element is not defined

### ISSUE THREAD

**Issue by mhaagens** [zendeskgarden/react-components#24]
## Expectations
I showed up, expecting to have my mind blown.
Universal Express, Webpack and React app, trying to use the React components.

## Reality
But all I got was this lousy
![screen shot 2018-05-25 at 12 05 51](https://user-images.githubusercontent.com/3270517/40539122-0158cc12-6014-11e8-8504-f4f9548c5470.png)

## Steps to Reproduce

1. yarn add @zendeskgarden/react-select
2. import Select from "@zendeskgarden/react-select";
3. Cry

###### Fine Print

* Component: 
* Browser: all
* Environment: Node + Browser

**Comment by austin94** [comment]
:wave: Hi @mhaagens, thanks for opening this issue. I have a feeling this is related to #10 as well.

Currently, we have several issues with server-side rendering:

* We are requiring consumers to handle our CSS-modules logic.
  * This is going to be corrected in a build update that you can look through at #21 
  * This will hopefully simplify the amount of webpack changes needed to consume us
* Our `@zendeskgarden/react-theming` package, specifically `<ThemeProvider>`, includes a `<StyleSheetManager>` from styled-components and some browser only logic (document.head, Element, etc.)
  * This logic should always be included by the consumer, so we will need to rip out the browser-only logic
  * We currently don't have a public issue for tracking this, so I think we can track it with this issue

Once both of these are complete I think this should resolve the issues you have seen.

If you want a quick environment to play around with, take a look at https://stackblitz.com/edit/garden-with-create-react-app-beta in the meantime.

**Comment by mhaagens** [comment]
Thanks for getting back to me Austin!
Looking forward to seeing the issues resolved, really like the UI framework and yeah, minimising custom webpack configuration would definitely help adoption. If you're already using styled-components to style the components might you be able to expose the theme directly so it can be utilized by those already using styled-components and a <ThemeProvider />?

**Comment by austin94** [comment]
Just to update this issue some:

* ~~We are requiring consumers to handle our CSS-modules logic~~

This was completed with https://github.com/zendeskgarden/react-components/commit/8584e7359e72a6077bbfc3a0f3e24b6090c1d497 and it's associated `major` versions.

* `@zendeskgarden/react-theming` package includes some bad `styled-components` logic

This is still in the backlog and I hope we are able to prioritize it in the near future, but no timeline yet on removing that functionality.

> If you're already using styled-components to style the components might you be able to expose the "theme" directly so it can be utilized by those already using styled-components

I think I might be confused by this.  We currently provide a `theme` prop on the [theme-provider](https://garden.zendesk.com/react-components/theming/#themeprovider) which allows you to inject styling directly as well as make it available with the `retrieveTheme` utility.

One other point is that our components actually don't use a set `theme`. Since we provide all of the base styling with `css-modules` we don't have a set way of theming, just a way of easily injecting generic styling.
