### ISSUE TITLE
Inconsistent scroll behavior with Modal in Internet Explorer

### ISSUE THREAD

**Issue by jpandl19** [zendeskgarden/react-components#267]
## Expectations
The Modal scroll behavior works the same in Internet Explorer as it does in the other browsers.

### Massive Modal in Chrome
![chrome_massive_modal](https://user-images.githubusercontent.com/11040668/52735163-cc810080-2f7b-11e9-8d5f-0b8d1a812f8a.gif)

### Massive Modal in Internet Explorer
Notice the `Header` has disappeared. If you scroll up, the `Footer` will scroll out of view.
![image](https://user-images.githubusercontent.com/11040668/52735026-7613c200-2f7b-11e9-8c38-c0884803a60a.png)

## Steps to Reproduce

  1. Open the Garden React [Modal documentation](https://garden.zendesk.com/react-components/modals/) on Internet Explorer
  1. Add a bunch of content to the Modal body (enough so that it overflows)
  1. Notice that the entire modal scrolls. In other browsers only the body scrolls. This causes IE users to miss content within the `Footer` 

###### Fine Print

* Component: [Modal](https://garden.zendesk.com/react-components/modals/)
* Browsers: Internet Explorer

**Comment by jzempel** [comment]
@jpandl19 this is a bug with IE11 with flexbox, fixed positioning, and height. We specify 100% for the height of the body – which works in most browsers. You can override this in your particular case by setting the expected height, in pixels, of the body – so `<Body style={{height: 300}}>` for example.

**Comment by jzempel** [comment]
p.s. not crucial to the issue at hand, but we should be seeing `<Modal large>` styling here.

**Comment by jpandl19** [comment]
Hey @jzempel thanks for looking into this. I tried overriding the body height but we end up getting dual scrollbars in IE on smaller screens.

#### `<Body style={{height: 300}}>` in IE
![image](https://user-images.githubusercontent.com/11040668/53213016-2b89e980-35fc-11e9-9e02-b0524fd0bf5a.png)


For our particular use case we are setting `100vh` on the `Body` so that it takes up the entire screen. Ideally, we'd get something that behaves like this (as it does in Chrome, Firefox, Safari): 
![image](https://user-images.githubusercontent.com/11040668/53212948-cc2bd980-35fb-11e9-88f3-91db10f1410e.png)

Or we could chalk this up as a known limitation of IE?


> We should be seeing `<Modal large>` styling here

Good call updated it to large in this example.

**Comment by jzempel** [comment]
@jpandl19 not sure what's going on, but this works just fine for me (no double scroll bars).

![screen shot 2019-02-22 at 2 11 44 pm](https://user-images.githubusercontent.com/143773/53274384-ee7d3000-36ab-11e9-83e9-dcbc256e2b3f.png)

**Comment by ryanseddon** [comment]
I get the double scrollbar too. It only appears when the viewport height is less that the height set on `<Body>`.

**Comment by ryanseddon** [comment]
The double scroll is due to the `overflow: auto` on the `.c_dialog`. Removing it in the IE11 dev tools causes more weird rendering issues so I assume it is there for good reason.

https://github.com/zendeskgarden/css-components/blob/eaaf515310df8484b8cebc1ead9bbba664a37bcc/packages/modals/src/_backdrop.css#L45-L52

![screen shot 2019-02-25 at 11 30 45 am](https://user-images.githubusercontent.com/143402/53307885-d0ecd800-38f0-11e9-9cfb-f281211bd218.png)

**Comment by jzempel** [comment]
You'll need to apply a `min-height` to your `<Modal>` to equal the expressed body height + header height + footer height. So in my example of 300px body, I think it's something like `<Modal style={{minHeight: 508}}>` in order to knock out the double scroll. Totally doable, but you'll need to manage your own heights wrt extreme screen sizing, etc.

Another option is that you don't support body-only scrolling for IE11 :wink:

**Comment by jzempel** [comment]
I'm closing this as resolved. Please re-open if there are ongoing concerns.
