### ISSUE TITLE
ButtonGroup double focus

### ISSUE THREAD

**Issue by jzempel** [zendeskgarden/react-components#43]
## Expectations

A `<ButtonGroup>` should never allow focus on more than one item.

## Reality

With some amount of effort, you can break focus styling for buttons.

## Steps to Reproduce

1. Mouse down on the last button within a `<ButtonGroup>`
1. Drag off of the button and then mouse up
1. Switch to a new tab and then return

Result: both the first and last button will style with a focus state.

![double-focus](https://user-images.githubusercontent.com/143773/41489230-17b56236-70a4-11e8-873d-afd2943195a3.gif)

###### Fine Print

* Component: 
* Browsers: all

**Comment by ryanseddon** [comment]
So I had a look around in this, pretty sure the culprit is `SelectionContainer` doing a few things.

Clicking and dragging like you have with the last element gives it true browser focus `document.activeElement` returns the last button. What happens when clicking out of the window means it triggers the `onBlur` which clears the selection model state. On window focus the default selection is the first item but the true focus restored by the browser is still the 3rd button. Thats how we get the double focus.

### Potential fix

Most likely to check the `document.activeElement` on focus and alter the default if that is child of the button group
