### ISSUE TITLE
Simplify Tabs Adjustments

### ISSUE THREAD

**Issue by louisscruz** [zendeskgarden/react-components#550]
## Expectations

It should be easy to adjust small stylistic details of the default `<Tabs />` implementation.

## Reality

Currently, you either have to apply manual styling child selectors to reach the internal div `data-garden-id="tabs.tablist"` or eject into full control and views usage in order to adjust its styling when using a `<Tabs />`. This is a pretty extreme cost if `<Tabs />` state management is doing everything right and then you just want to modify something like the margin of the list.

Maybe some kind of `tabListProps` could be provided? Or maybe the `<Tabs />` could somehow operate differently if its children is a `<TabList />`. Or maybe I totally missed some simple and non-brittle way out that currently exists, but it's hard to tell with the current documentation.

## Steps to Reproduce

1. Use `<Tabs />` to render some tabs.
2. Try to adjust the margin of the `<TabsList />`.

### Fine Print

- Component: `<Tabs />`
- Version: latest (7.1.2)
- Browsers: all

**Comment by austin94** [comment]
👋 Hi @louisscruz. We've been tracking an internal issue for this for quite some time. Rather than include a special prop to spread the values we've opted to update the API to match the DOM structure. This aligns with some of the new packages.

You can view the "new" API at https://github.com/zendeskgarden/react-components/blob/next/packages/tabs/examples/default-tabs.md Since this is a breaking change we've been waiting to merge this until v8.

The new API:

```tsx
<Tabs>
  <TabList>
    <Tab item="unique-value-1">Item 1</Tab>
    <Tab item="unique-value-2">Item 2</Tab>
  </TabList>
  <TabPanel item="unique-value-1">Tab 1 content</TabPanel>
  <TabPanel item="unique-value-2">Tab 2 content</TabPanel>
</Tabs>
```

will allow a consumer to apply custom props (and styling via Fela or styled-components) to the `TabList` element directly.

**Comment by louisscruz** [comment]
Makes sense, thanks! 👍
